# Generated by Django 5.2.7 on 2025-10-27 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('init_duration', models.DateTimeField()),
                ('effective_duration', models.DateTimeField()),
                ('effective_end_time', models.DateTimeField()),
                ('true_end_time', models.DateTimeField(default=None, null=True)),
                ('status', models.IntegerField(choices=[('Finished', 'Finished'), ('Running', 'Running'), ('Paused', 'Paused')], default='Running')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
