# Generated by Django 5.2.7 on 2025-10-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='effective_duration',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='timer',
            name='init_duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='timer',
            name='true_end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
