# Generated by Django 5.2.7 on 2025-10-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0002_alter_timer_effective_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='status',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Running', 'Running'), ('Paused', 'Paused')], default='Running', max_length=16),
        ),
    ]
