# Generated by Django 5.2.7 on 2025-10-27 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0003_alter_timer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='true_end_time',
        ),
        migrations.AlterField(
            model_name='timer',
            name='effective_duration',
            field=models.DurationField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='timer',
            name='effective_end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timer',
            name='init_duration',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='timer',
            name='status',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Running', 'Running'), ('Paused', 'Paused')], default='Running', max_length=12),
        ),
    ]
