# Generated by Django 5.2.7 on 2025-10-27 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0004_remove_timer_true_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='effective_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name='timer',
            name='effective_end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 27, 17, 29, 54, 667096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timer',
            name='init_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
