# Generated by Django 5.2.7 on 2025-10-27 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0005_alter_timer_effective_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='effective_end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 27, 18, 38, 25, 460275, tzinfo=datetime.timezone.utc)),
        ),
    ]
