# Generated by Django 5.2.7 on 2025-10-28 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0006_alter_timer_effective_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='title',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='timer',
            name='effective_end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 28, 10, 53, 2, 570700, tzinfo=datetime.timezone.utc)),
        ),
    ]
