# Generated by Django 5.2.7 on 2025-11-19 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0007_timer_title_alter_timer_effective_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='effective_end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 19, 21, 6, 18, 800418, tzinfo=datetime.timezone.utc)),
        ),
    ]
