# Generated by Django 5.2.7 on 2026-02-13 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0008_alter_timer_effective_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='effective_end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 17, 5, 5, 711825, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timer',
            name='status',
            field=models.CharField(choices=[('Running', 'Running'), ('Paused', 'Paused'), ('Finished', 'Finished'), ('Deletion', 'Deletion')], default='Running', max_length=12),
        ),
    ]
