# Generated by Django 5.2.7 on 2026-02-28 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0009_alter_timer_effective_end_time_alter_timer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='effective_end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 28, 17, 10, 20, 996490, tzinfo=datetime.timezone.utc)),
        ),
    ]
