# Generated by Django 5.2.7 on 2026-02-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0010_alter_timer_effective_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='effective_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='timer',
            old_name='created_at',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='timer',
            old_name='status',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='effective_end_time',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='init_duration',
        ),
    ]
