# Generated by Django 5.2.7 on 2026-02-28 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0011_rename_effective_duration_timer_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='last_pause_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='timer',
            name='total_paused_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='timer',
            name='state',
            field=models.CharField(choices=[('Running', 'Running'), ('Paused', 'Paused'), ('Finished', 'Finished')], default='Running', max_length=12),
        ),
    ]
