# Generated by Django 5.2.7 on 2026-02-28 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0012_timer_last_pause_time_timer_total_paused_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
